# Generated by Django 3.2.13 on 2022-06-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paralleltext',
            name='vocab_map',
            field=models.TextField(default='словарь', verbose_name='словарь'),
        ),
    ]
