# Generated by Django 3.2.13 on 2022-06-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_paralleltext_vocab_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='paralleltext',
            name='showOnSite',
            field=models.BooleanField(default=False, verbose_name='Показывать на сайте'),
        ),
    ]
