# Generated by Django 3.2.3 on 2022-07-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_paralleltext_showonsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='HanZi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.TextField(default='', verbose_name='иероглиф')),
                ('reading', models.TextField(default='', verbose_name='чтение')),
                ('translation', models.TextField(default='', verbose_name='перевод')),
            ],
        ),
    ]
